GRID_SEARCH_CV="grid"
RANDOMIZED_SEARCH_CV="randomized"
XMIN=0
XMAX=255
DATA_FOLDER_PATH= r"your data folder path/Fashion MNIST images"
FASHION_MNIST_TRAIN="fashion_mnist_train.csv"
FASHION_MNIST_TEST="fashion_mnist_test.csv"
TARGET_COLUMN_NUMBER=1
THRESHOLD_ACCURACY_SCORE=86
FASHION_MNIST_MODEL_FILE="fashion_mnist_ann_classification.pkl"
HORIZONTAL="horizontal"
VERTICAL="vertical"